setup: ddm

experiment:
  run_name: DDPM_Conditional
  device: cuda


# Dataset
dataset:
  train_path: /mnt/Data/Datasets/Images/CIFAR10/cifar10-64/train
  val_path: /mnt/Data/Datasets/Images/CIFAR10/cifar10-64/test
  image_size: 64

model:
  num_classes: 10
  ema_beta: 0.995

training:
  batch_size: 16
  epochs: 500
  logging_freq: 2
  workers: 3

optimizer:
  lr: 3.0e-4
